# Generated by Django 4.0.5 on 2023-04-26 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addpostmodel',
            name='user_id',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
