# Generated by Django 4.0.5 on 2023-04-27 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0002_alter_addpostmodel_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='addpostmodel',
            name='tech',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
